{% set name = "wikipedia_ql" %}
{% set version = "0.0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wikipedia_ql-{{ version }}.tar.gz
  sha256: 6f78987f526b6fe36b425c2b1d424bc6e078fd0ef436a46c431bc6af14cc82df

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - poetry >=0.12
    - pip
    - python {{ python_min }}
  run:
    - bs4 >=0.0.1
    - lark >=0.11.3,<0.12.0
    - nltk >=3.6.2,<4.0.0
    - python >={{ python_min }}
    - pyaml >=21.10.1,<22.0.0
    - requests >=2.25.1,<3.0.0
    - soupsieve >=2.3.1,<3.0.0

test:
  source_files:
    - tests
  imports:
    - wikipedia_ql
  commands:
    - pip check
    - python -c "import nltk; nltk.download('punkt')"
    - pytest -vvv --capture=tee-sys -k 'not rotten_tomatoes and not test_category and not test_follow_links and not test_table_filmography and not test_simple' tests
  requires:
    - pip
    - pytest >=5.2
    - python {{ python_min }}

about:
  home: https://github.com/zverok/wikipedia_ql
  summary: Query Language for Wikipedia
  license_file: LICENSE
  license: MIT

extra:
  recipe-maintainers:
    - thewchan
